

DROP TABLE T_JL_CLIENTE;
CREATE TABLE T_JL_CLIENTE
(
ID_CLIENTE NUMERIC(9) NOT NULL,
NM_CLIENTE VARCHAR2(80) NOT NULL,
DT_ENTRADA DATE NOT NULL,
DT_SAIDA DATE NOT NULL,
NR_CPF NUMBER(12) NOT NULL,
DS_SEXO CHAR(1) NOT NULL
);
ALTER TABLE  T_JL_CLIENTE 
    ADD CONSTRAINT PK_JL_CLIENTE PRIMARY KEY (ID_CLIENTE);

ALTER  TABLE T_JL_CLIENTE_EMAIL
    ADD CONSTRAINT FK_JL_CLIENTE_EMAIL FOREIGN KEY (ID_CLIENTE)
    REFERENCES T_JL_CLIENTE(ID_CLIENTE);
    
ALTER TABLE  T_JL_CLIENTE
    ADD CONSTRAINT CK_JL_CLIENTE_SEXO CHECK ( DS_SEXO IN ('F','M','I'));
    
ALTER TABLE T_JL_CLIENTE
    ADD CONSTRAINT UK_JL_CPF_CLIENTE UNIQUE (NR_CPF);

    
COMMENT ON COLUMN T_JL_CLIENTE.ID_CLIENTE IS
    'ESTE ATRIBUTO IRRÁ RECEBER A CHAVE PRIMÁRIA DO CLIENTE. NÚMERO GERADO SEQUÊNCIALMENTE PELO SITEMA. 
SEU CONTEÚDO É OBRIGATÓRIO.';

COMMENT ON COLUMN T_JL_CLIENTE.NM_CLIENTE IS
    'ESTE ATRIBUTO IRÁ RECEBER O NOME COMPLETO DO PACIENTE. SEU CONTEÚDO É OBRIGÁTÓRIO.';
    
COMMENT ON COLUMN T_JL_CLIENTE.NR_CPF IS
    'ESTE ATRIBUTO IRÁ RECEBER O NÚMERO DO CPF DO PACIENTE. SEU CONTEÚDO É OBRIGATÓRIO E SERÁ VALIDADE DE ACORDO COM REGRAS 
DE NEGÓCIO';

COMMENT ON COLUMN T_JL_CLIENTE.DS_SEXO IS
    'ESTE ATRIBUTO IRÁ RECEBER O SEXO DO PACIENTE. SEU CONTEÚDO É OBRIGATÓRIO';
    
COMMENT ON COLUMN T_JL_CLIENTE.DT_ENTRADA IS
    'ESTE ATRIBUTO IRÁ RECEBER A DATA DE ENTRADA DO CLIENTE. SEU CONTEÚDO É OBRIGATÓRIO.';
COMMENT ON COLUMN T_JL_CLIENTE.DT_SAIDA IS
    'ESTE ATRIBUTO IRÁ RECEBER A DATA DE SAÍDA DO CLIENTE. SEU CONTEÚDO É OBRIGATÓRIO.';

TRUNCATE TABLE T_JL_DEPTO;

DROP TRIGGER SQ_JL_DEPTO;
DELETE FROM T_JL_DEPTO WHERE ID_DEPTO > 5;

DROP TABLE T_JL_DEPTO;
CREATE TABLE T_JL_DEPTO
(
ID_DEPTO NUMBER(9),
NM_DEPTO VARCHAR(30),
SG_DEPTO CHAR(3),
ST_DEPTO CHAR(1)
);
DROP SEQUENCE  SQ_JL_DEPTO;
CREATE SEQUENCE SQ_JL_DEPTO
START WITH 1
MAXVALUE 7;

INSERT INTO T_JL_DEPTO(ID_DEPTO, NM_DEPTO, SG_DEPTO, ST_DEPTO)
VALUES (1, 'FINANCEIRO','FN','A');

INSERT INTO T_JL_DEPTO(ID_DEPTO, NM_DEPTO, SG_DEPTO, ST_DEPTO)
VALUES (2, 'CONTABILIDADE','CTB','A');

INSERT INTO T_JL_DEPTO(ID_DEPTO, NM_DEPTO, SG_DEPTO, ST_DEPTO)
VALUES (3, 'JURIDICO','JR','A');

INSERT INTO T_JL_DEPTO(ID_DEPTO, NM_DEPTO, SG_DEPTO, ST_DEPTO)
VALUES (4, 'RECURSOS HUMANOS','RH','A');

INSERT INTO T_JL_DEPTO(ID_DEPTO, NM_DEPTO, SG_DEPTO, ST_DEPTO)
VALUES (5, 'ORÇAMENTOS','OR','A');

INSERT INTO T_JL_DEPTO(ID_DEPTO, NM_DEPTO, SG_DEPTO, ST_DEPTO)
VALUES (6, 'PRODUÇÃO','PD','A');

INSERT INTO T_JL_DEPTO(ID_DEPTO, NM_DEPTO, SG_DEPTO, ST_DEPTO)
VALUES (7, 'TECNOLOGIA DA INFOMAÇÃO','TI','A');

ROLLBACK;
COMMIT;

SELECT * FROM T_JL_DEPTO;
SELECT * FROM T_JL_DEPTO ORDER BY ID_DEPTO;







ALTER TABLE T_JL_DEPTO ADD ST_TESTE_DEPTO CHAR(1);
UPDATE T_JL_DEPTO SET ST_TESTE_DEPTO = 'A';
SELECT * FROM T_JL_DEPTO;

ALTER TABLE T_JL_DEPTO MODIFY(ST_TESTE_DEPTO CONSTRAINT CK_JL_DEPTO_ST_DEPTO_NN NOT NULL);
ALTER TABLE T_JL_DEPTO ADD CONSTRAINT CK_JL_DEPTO_ST_DEPTO CHECK (ST_TESTE_DEPTO IN ('A','I'));





INSERT ALL 
    INTO T_JL_DEPTO(ID_DEPTO, NM_DEPTO, SG_DEPTO, ST_DEPTO, ST_TESTE_DEPTO)
    VALUES (8, 'MARKETING', 'MKT', 'I', 'I')
    INTO T_JL_DEPTO(ID_DEPTO, NM_DEPTO, SG_DEPTO, ST_DEPTO, ST_TESTE_DEPTO)
    VALUES (9, 'ESPORTE', 'ESP', 'I', 'I')
    INTO T_JL_DEPTO(ID_DEPTO, NM_DEPTO, SG_DEPTO, ST_DEPTO, ST_TESTE_DEPTO)
    VALUES (10, 'GAMES CORPORATIVOS', 'GMC', 'I', 'I')
SELECT * FROM DUAL;
SELECT * FROM T_JL_DEPTO;







INSERT INTO T_JL_CLIENTE
(
ID_CLIENTE,
NM_CLIENTE,
DT_ENTRADA,
DT_SAIDA,
NR_CPF,
DS_SEXO
)
VALUES
(
1,
'YELSEW MIELK',
TO_DATE('28/01/1995','DD/MM/YYYY'),
SYSDATE,
42740502893,
'M'
);
SELECT * FROM T_JL_CLIENTE;
COMMIT;












INSERT INTO T_JL_DEPTO(ID_DEPTO, NM_DEPTO, SG_DEPTO, ST_DEPTO)
VALUES (SQ_JL_DEPTO.NEXTVAL, 'MANUTENÇÃO PREVENTIVA', 'MPV', 'A');

SELECT SQ_JL_DEPTO.CURVAL FROM DUAL;

INSERT INTO T_JL_DEPTO(ID_DEPTO, NM_DEPTO, SG_DEPTO, ST_DEPTO)
VALUES (SQ_JL_DEPTO.NEXTVAL, 'FINANCEIRO', 'FN', 'A');

SELECT SQ_JL_DEPTO.CURVAL FROM DUAL;

INSERT INTO T_JL_DEPTO(ID_DEPTO, NM_DEPTO, SG_DEPTO, ST_DEPTO)
VALUES (SQ_JL_DEPTO.NEXTVAL, 'CONTAS A PAGAR ', 'CP', 'A');

SELECT SQ_JL_DEPTO.CURVAL FROM DUAL;

INSERT INTO T_JL_DEPTO(ID_DEPTO, NM_DEPTO, SG_DEPTO, ST_DEPTO)
VALUES (SQ_JL_DEPTO.NEXTVAL, 'CONTAS A RECEBER', 'CR', 'A');

SELECT SQ_JL_DEPTO.CURVAL FROM DUAL;











DROP TABLE T_JL_CLIENTE_CONTATO;
CREATE TABLE T_JL_CLIENTE_CONTATO
(
ID_CONTATO NUMBER(9),
NM_CONTATO VARCHAR2(40),
NR_DDI NUMBER(3),
NR_DDD NUMBER(3),
NR_CONTATO NUMBER(10),
ST_CONTATO CHAR(1)
);

DROP TABLE T_JL_CLIENTE_EMAIL;
CREATE TABLE T_JL_CLIENTE_EMAIL
(
ID_EMAIL NUMBER(9),
DS_EMAIL VARCHAR(200),
NM_EMAIL VARCHAR(20),
ST_EMAIL CHAR(1)
);

DROP TABLE T_JL_CLIENTE_VEICULO;
CREATE TABLE T_JL_CLIENTE_VEICULO
(
ID_VEICULO NUMBER(9),
DS_PLACA VARCHAR2(7),
MD_VEICULO VARCHAR(10),
MC_VEICULO VARCHAR(10)
);



